### ISSUE TITLE
feature request: parse the timestamp in seconds

### ISSUE THREAD

**Issue by uriva** [1c7/srt-parser-2#13]
can use this:

```js
const srtTimestampToSeconds = (srtTimestamp) => {
  const [rest, millisecondsString] = srtTimestamp.split(",");
  const milliseconds = parseInt(millisecondsString);
  const [hours, minutes, seconds] = rest.split(":").map(x => parseInt(x));
  return milliseconds * 0.001 + seconds + 60 * minutes + 3600 * hours;
};
```

**Comment by 1c7** [comment]
try to make a pull request if you have the time

**Comment by uriva** [comment]
#14

**Comment by AlphaCodeZero** [comment]
@uriva I think you should make startSeconds and endSeconds optional, or it will break typescript checks in existent projects.

**Comment by uriva** [comment]
i disagree because the library always outputs these fields, so if you update this reflects the correct typing.

**Comment by AlphaCodeZero** [comment]
> i disagree because the library always outputs these fields, so if you update this reflects the correct typing.

It's not about outputs, it's about inputs. The toSrt method require an argument of type Line, which didn't need these two fields in v1.1.7. So if I don't lock version, I have to solve this type mismatch issue. I think this is a kind of break changes.

![image](https://user-images.githubusercontent.com/15966914/196142344-c5c7d940-4076-4257-be17-2f5646b8cbd8.png)

**Comment by uriva** [comment]
ah I see. you're right. so I'd recommend changing the typing on the `toSrt` function. Optionality increases options the programmer needs to reason about it, it's not really optional.

**Comment by cpboyd** [comment]
Note: the `interface Line` currently only applies to `toSrt`... It's not used anywhere else in the Typescript code
Wouldn't it make more sense to move the `Seconds` properties to a new `interface` that `extends Line` and specify that as the return value of `fromSrt`?
