### ISSUE TITLE
timestampToSeconds sometimes returns incorrect number

### ISSUE THREAD

**Issue by Fedduh** [1c7/srt-parser-2#16]
Hi,

I would love to use your library but I noticed some odd javascript rounding behaviour.

In this function
```javascript
const timestampToSeconds = (srtTimestamp: string) => {
  const [rest, millisecondsString] = srtTimestamp.split(",");
  const milliseconds = parseInt(millisecondsString);
  const [hours, minutes, seconds] = rest.split(":").map((x) => parseInt(x));
  return milliseconds * 0.001 + seconds + 60 * minutes + 3600 * hours;
};
```

When using the timestamp: 
```javascript
timestampToSeconds('00:01:20,460');
```

returns: 80.46000000000001

Actual calc is 460 * 0.001 + 20 + 60, which returns 80.46000000000001 in JS

I guess this is a JS perk. But can be overcome by doing some extra rouding in this function.
e.g. Math.round(80.46000000000001 * 1000) / 1000

Another example is this timestamp: 00:01:32,020

**Comment by 1c7** [comment]
I don't have time to fix this right now, would you mind send me a Pull Request?

**Comment by 1c7** [comment]
Thank you!

**Comment by 1c7** [comment]
I didn't look into code line by line, I just merge it.

**Comment by 1c7** [comment]
The newest version is [1.2.1](https://www.npmjs.com/package/srt-parser-2/v/1.2.1)
I would publish 1.2.2 soon (in a couple days)

**Comment by Fedduh** [comment]
Cool! Thanks :) I'll close the ticket after

**Comment by 1c7** [comment]
[v1.2.2](https://www.npmjs.com/package/srt-parser-2/v/1.2.2) has published
