### ISSUE TITLE
Improve how timestamps in seconds are handled

### ISSUE THREAD

**Issue by qgustavor** [1c7/srt-parser-2#18]
Issue #13 asked for implementing parsing timestamps in seconds, but there is an issue with that: the documentation shows an example of that, but do not explain which of `startTime` or `startSeconds` are used when converting back to a string.

One simple improvement is fixing the documentation by making this behavior clear.

Other complex improvement is also allowing to choose between one and other (maybe something like `parser.toSrt(srt_array, {useSeconds: true})`) and/or exposing a `secondsToTimestamp` method.

**Comment by 1c7** [comment]
would you mind to send a PR? I really don't have for time for this

**Comment by qgustavor** [comment]
I can send a pull request, it's not like I have a lot time of that too! 😅

I just need to know what to send: change the code or just the documentation? If you prefer changing the code, just expose a function to convert seconds to timestamps or add an option argument to `toSrt` that calls it too? My approach on my [ass-parser](https://github.com/qgustavor/ass-parser/) fork was to add an option to the parse function (akin to `fromSrt`) to return timestamps as numbers instead of strings, then the stringify function (akin to `toSrt`) just accepts both numbers or strings as timestamps and handle those accordingly, but this approach can't be taken here anymore.

**Comment by 1c7** [comment]
I don't know, I don't have time to think about this, just do whatever you think is appropriate, I can't guarantee I would have the time to review code & merge Pull request

**Comment by qgustavor** [comment]
I just forked the library: https://github.com/qgustavor/srt-parser

**Comment by 1c7** [comment]
That's the point of open sources! thanks for fork & improving the software
