### ISSUE TITLE
CLI not working

### ISSUE THREAD

**Issue by pedrospj** [1c7/srt-parser-2#19]
I use this **awesome** lib in  a personal project. I have only used intalled in the project, today I was trying to use the CLI version and noticed it was not working.

Command I ran: 
```
npx srt-parser-2 -i input.srt -o output.json --minify
```

Output:
```
(node:9952) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\ppedr\AppData\Local\npm-cache\_npx\b731975f552886f1\node_modules\srt-parser-2\bin\index.js:4
import { readFile, writeFile } from "fs/promises";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

Machine information:
OS: Windows 10
Node: v18.16.0

---

I'm trying to fix this error and will open a PR if a manage to do it.

**Comment by 1c7** [comment]
> I'm trying to fix this error and will open a PR if a manage to do it.
Thanks!

**Comment by pedrospj** [comment]
@1c7 done! It was just a small bug.

**Comment by 1c7** [comment]
The newest version is 1.2.2, I would releast 1.2.3 soon

**Comment by 1c7** [comment]
<img width="1269" alt="image" src="https://github.com/1c7/srt-parser-2/assets/1804755/9424c9dd-f65f-40b9-a043-8fdbacec1e23">

**Comment by 1c7** [comment]
done 1.2.3 has been released
https://www.npmjs.com/package/srt-parser-2/v/1.2.3
