### ISSUE TITLE
[Enhancement] Improvements in code

### ISSUE THREAD

**Issue by pedrospj** [1c7/srt-parser-2#21]
While working on a bug, I had some suggestions I'd like to implement in this lib.

- Replace `mocha `/ `chai `with `vitest`. [Vitest](https://github.com/vitest-dev/vitest) is a modern test runner powered by Vite. It runs TS easily.
- Replace all `var` statements with `let`/`const`
- Add code documentation (JSDocs) (to see comments if you hover the function)

Are these changes of any interest? If so, I'd be happy to help and open PRs from time to time implementing them.

**Comment by 1c7** [comment]
Sure, great suggestion, I would merge your PR (if test passed)

**Comment by 1c7** [comment]
I am in UTC+8 Timezone

**Comment by pedrospj** [comment]
I am in UTC-3, It will take some time to implement all thing because I'll have to do it in my spare time. But long live this lib 🚀
