### ISSUE TITLE
Feature request: Add CLI script

### ISSUE THREAD

**Issue by chaitanya-deep** [1c7/srt-parser-2#5]
I have an SRT file I wanted to quickly parse and output as a JSON.
I was hoping for something like this without creating a new project
```
npm install -g srt-parser-2
srt-parser-2 -i input.srt -o output.json
```

It's possible to do this with a `bin` entry in package.json pointing to a node script.
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#bin

Is this a planned feature or would you be interested in adding it to the package? I can try make a PR for it if needed

**Comment by 1c7** [comment]
I don't have time to add this feature, you can fork & make a PR :)
